[images]
  remote_images = ["https://images.unsplash.com/*"]

[build]
  command = "bun run build"
  publish = "dist"

[dev]
  command = "bun run dev"
  port = 5173
  targetPort = 5173
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
